[package]
name = "yclass-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true

memflex = { version = "0.7.0", features = ["external"] }
thiserror = "1.0.47"
bytemuck = "1.13.1"
logos = "0.13.0"
